### ISSUE TITLE
Stream preview formatting error

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub-modules-wiki#102]
Formatting is not applied if there is to much text in the (stream) preview field. Instead the Markdown commands are shown e.g. **Text

**Comment by buddh4** [comment]
Can you give me an example to recreate? Do you mean only the last line is not formatted. My example woked fine:

![grafik](https://user-images.githubusercontent.com/9800854/67779085-7221c480-fa64-11e9-8f3d-341d1f772fba.png)

**Comment by Oremountainflorian** [comment]
I also faced this issue when members were linked within an wiki page via "@" in the first lines which were shown in the stream. 

But I guess the it was solved and can be closed. Thank you for that! :)

**Comment by buddh4** [comment]
I think its a general issue with cutting richtext output to a certain length. We should rather think of another presentation of wiki pages in the stream.

**Comment by Oremountainflorian** [comment]
![grafik](https://user-images.githubusercontent.com/44228345/102461822-40ddcc80-4049-11eb-865f-56d21888d763.png)

**Comment by buddh4** [comment]
I'am currently working on proper conversion of richtext for 1.8. Proper preview rendering will be part of this change.

**Comment by buddh4** [comment]
I'll close for now since this issue is not directly related with the wiki modul. I'll document the changes in the pull request: https://github.com/humhub/humhub/pull/4686
