### ISSUE TITLE
Line breaks in tables

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub-modules-wiki#108]
Line breaks in tables are not applied

HH 1.3.15
Wiki 1.3.10

**Comment by buddh4** [comment]
Will be fixed in HumHub v1.4

**Comment by st5000** [comment]
@buddh4 fixed in HH 1.4 stable ?

FYI, issue still actually present in HH 1.4-beta.1

**Comment by buddh4** [comment]
Will be fixed in 1.4 beta.2
