### ISSUE TITLE
Installation failed on humhub

### ISSUE THREAD

**Issue by gonley** [humhub/humhub-modules-wiki#116]
![Capture](https://user-images.githubusercontent.com/5567604/78563810-1eef4180-784e-11ea-83b0-54dcaa95f8e9.PNG)

I have faced this issue which causes installation failed. Is there any issue? My humhub version is 1.4.4 and the wiki version I try to install is 1.3.10

**Comment by luke-** [comment]
Are you able to install other modules?
What happens if you try it again?

**Comment by gonley** [comment]
> Are you able to install other modules?
> What happens if you try it again?

Yes. There are some other modules consisting of this issue. So I think that I should increase max_execution_time in php setting, and yes, it solves the issue. Thanks for your help also.
