### ISSUE TITLE
[bug] Table <td> auto adds "<br>" after a text

### ISSUE THREAD

**Issue by warshell** [humhub/humhub-modules-wiki#123]
1. In editor: Creating a 2 rows table with a text in each . (everything is ok )
2 Saving and my table have a extra br

![image](https://user-images.githubusercontent.com/617020/80303440-a0cced80-87b0-11ea-9f1f-0e4ec2d05815.png)

is this a feature or a bug ? How to remove it ? thanks

**Comment by Oremountainflorian** [comment]
@devcline This "bug" was already mentioned in issue https://github.com/humhub/humhub-prosemirror/issues/11 of humhub prosemirror repo

**Comment by buddh4** [comment]
Is fixed in HumHub 1.5.2
