### ISSUE TITLE
[Minor bug] Copy text from stream to wiki page inserts blank lines

### ISSUE THREAD

**Issue by Oremountainflorian** [humhub/humhub-modules-wiki#127]
## Problem description

Copying text from stream to a wiki page, additional blank lines are added. Doesn't occur when content is copied from a saved wiki page to edit mode of a page. 

## Steps to reproduce

OS: Win 8.1
Browser: Firefox 75
Version: HumHub 1.5.1

- Create a wiki page
- Write some text lines separated by enter
- Save
- Go to stream
- Copy the preview 
- Paste it to another wiki page

Beetween the lines, a blank line is inserted. At the beginning two blank lines are inserted. Once you save it, the blank lines are removed (as it always happens with blank lines beetween text)

### <ins>↓Stream↓</ins>
![grafik](https://user-images.githubusercontent.com/44228345/80679727-b77b8900-8abd-11ea-8553-520b7edc771c.png)

### <ins>↓As it looks pasted into the editor↓</ins>
![grafik](https://user-images.githubusercontent.com/44228345/80679789-e09c1980-8abd-11ea-82c6-94bd030614c5.png)

**Comment by buddh4** [comment]
There is an overview richtext issue assembling usability and other enhancements issues. The copy/past issue already part:
https://github.com/humhub/humhub/issues/4215
