### ISSUE TITLE
import md-files into wiki possible?

### ISSUE THREAD

**Issue by beyring** [humhub/humhub-modules-wiki#128]
Hi all,

as I couldn't find a documentation for the wiki besides readme and changelog: Is it possible to import md-files into the wiki module?

Thanks in advance and best from Munich,
Ben

**Comment by luke-** [comment]
Servus!

The Wiki module itself does not support this, but you may be able to use the REST module to implement an import.

https://www.humhub.com/en/marketplace/rest/docs/html/wiki.html#tag/Wiki-Page/paths/~1wiki~1container~1{id}/post
(I don't know how stable the Wiki REST endpoint is.)

**Comment by beyring** [comment]
perfect. Thanx for the the quick reply.

**Comment by buddh4** [comment]
You should also be able to copy/past markdown into the richtext.
