### ISSUE TITLE
Scroll to the top

### ISSUE THREAD

**Issue by MasterMindNET** [humhub/humhub-modules-wiki#133]
Good day!

I believe I would come in handy to create some sort of a button, which brings users to the top in the article height is more than 2000 px or so.

Thank you!

**Comment by buddh4** [comment]
Maybe we could pimp the [scrollup](https://github.com/GreenMeteor/humhub-scrollup-module) to work in such module views. But I think there should not be a direct link between those modules. Ideally there are specific core layouts this module should be able to detect.

**Comment by MasterMindNET** [comment]
> Maybe we could pimp the [scrollup module](https://github.com/GreenMeteor/humhub-scrollup-module) to work in such module views. But I think there should not be a direct link between those modules. Ideally there are specific core layouts this module should be able to detect.

So, by this, you mean in case this module is installed on my project, it should in automatic order detect the page and add the scroll up button, isn't it?

**Comment by buddh4** [comment]
The scrollup module currently only works on dashboard and space stream, since in those views it knows how to calculate its horizontal position (aliged to the sidebar), also we want to prevent the scrollup button to interfer with any custom module ui components (e.g. overlap wiki menu etc.)

**Comment by MasterMindNET** [comment]
Good, so, Is there any way I can add some of the `events` to run the scroll-up widget to show this button?

AFAIK there is a `config.php` file that handles the init or other events for other modules...
I believe there should similar line of code to  `['class' => LayoutAddons::class, `...
```
    'events' => [
        ['class' => LayoutAddons::class, 'event' => LayoutAddons::EVENT_INIT, 'callback' => [Events::class, 'onLayoutAddonsInit']],
    ]
```
Could you advise me which event should I use to display in on the wiki view item?


> also we want to prevent the scrollup button to interfere with any custom module UI components (e.g. overlap wiki menu etc.)
To avoid overlap and other issues I can add some CSS code in a wiki module to move this button to some of the feasible  places

**Comment by luke-** [comment]
@MasterMindNET In the layout event you could check and do:

```php

if (Yii::$app->controller->module->id === 'wiki' && Yii::$app->controller->id == 'dont know yet') {
      // Do some wiki related stuff:
      // Yii::$app->view->registerCss  
}

```

Hope this helps!

**Comment by MasterMindNET** [comment]
Hello, @luke- 

Please, take a look at the [scrollup module](https://github.com/GreenMeteor/humhub-scrollup-module/pull/15#event-3649674814).
It has been merged, check this out when you have time, and I believe this could be closed if everything is considered to be done.

Thank you!

**Comment by luke-** [comment]
Thanks that looks good and should be done with the next ScrollUp release. 
Additionally we plan to revise the Wiki module from the UI in the near future.

**Comment by MasterMindNET** [comment]
> > The scrollup module currently only works on dashboard and space stream
> 
> In all honesty the Scroll up function should also work on the profile stream as well as those two view points 🤔

Sorry for that. Yeah it works excellent there!
