### ISSUE TITLE
Images broken after Upgrade from 1.10

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-wiki#135]
After an update of the Wiki module from 1.10 to 1.3.13 all embedded images are broken.
(The Richtext Editor always displays the image correctly.)

When I change e.g.
`![Filesystem.png](file-guid-f74306bd-b2bc-440b-84a6-d8ae8aa0da67)` to `![Filesystem.png](file-guid:f74306bd-b2bc-440b-84a6-d8ae8aa0da67)` manually in the `wiki-revision.content` database field  all images will reappear.

Following SQL Statement also fixes the problem for all wiki pages:
```
update wiki_page_revision  set content = replace(content, '](file-guid-', '](file-guid:');
```

Should we provide a migratoin here?

**Comment by buddh4** [comment]
We could allow `-` as seperator in the core?
