### ISSUE TITLE
Wall Stream Layout Migration - HumHub 1.7

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-wiki#139]

**Comment by yurabakhtin** [comment]
![Uploading preview_module_wiki.png…]()

**Comment by luke-** [comment]
Looks good so far. Can you remove the double title here?

**Comment by yurabakhtin** [comment]
@luke- Commit https://github.com/humhub/humhub-modules-wiki/pull/142/commits/a620d664e3c643d78d20b7d4e22be8ecc64c8af0 :
<img width="761" alt="fixed_wall_layout" src="https://user-images.githubusercontent.com/6995524/96476379-c9a0dd80-123d-11eb-89ca-a821084c7000.png">

**Comment by buddh4** [comment]
@luke- Didn't we consider removing the wiki content in the wall entry?

**Comment by luke-** [comment]
@buddh4 We have postponed it. The Wiki module will be on the agenda soon anyway.
