### ISSUE TITLE
Wiki character limit on page after a certain amount of words - text does not appear to save and the page seems to max out

### ISSUE THREAD

**Issue by haroldlucero** [humhub/humhub-modules-wiki#145]
It appears that we have stumbled across some sort of 'character limit' as, after a certain amount of words the text that has been uploaded does not appear to save and the page seems to max out. When this occurs, we click save and then lose all of the text that was below the cutoff point. Do anyone know anything about this? If it is helpful, when it happened it maxed out the page at 62,995 characters (with spaces).

Is this a limitation on the wiki? or a problem that can either be configured via the Admin panel or needs to be resolved?

**Comment by MasterHans** [comment]
Hi everyone!
The problem is in the limitation of **content** field in **wiki_page_revision** table.
The content column has the type **TEXT**. This type in MySQL has a maximum length equal to ~64kb.

We have to approach to solve it
1) Make content field type **MEDIUMTEXT** ~16MB or **LONGTEXT** ~4Gb.
2) Make settings on the Administration page to limit the text field and somehow warn users when the limit exceeded.

@luke-  what should I do?

**Comment by luke-** [comment]
@MasterHans I think we should increase to MEDIUM_TEXT? Are there reasons against it?

**Comment by MasterHans** [comment]
> @MasterHans I think we should increase to MEDIUM_TEXT? Are there reasons against it?

I think that would be perfect choice

**Comment by haroldlucero** [comment]
Thank you @MasterHans and @luke- for looking into this problem -- I run a hosted environment and do not have direct access to the instance/DB -- will this be a change that will be made to the Core branch and a future update via the Module? -- If we make the change (i.e. increase to MEDIUM_TEXT) in our hosted instance only, once a new core upgrade is made we may lose the changes -- what would be your best suggestion to make the change permanent? - -Thank you once again for looking into this - Kind Rgds Harold

**Comment by luke-** [comment]
The problem should then be solved automatically. But we have to release a new module version first.

**Comment by luke-** [comment]
In the meantime you can manually upload this file:
https://github.com/humhub/humhub-modules-wiki/blob/master/migrations/m201125_034854_alter_content_type_in_wiki_page_review.php

An run: Administration -> Information -> Databases
