### ISSUE TITLE
Misaligned display with many topics

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-wiki#157]
It would probably be nicer to display the topics in a separate line, if available.

![image](https://user-images.githubusercontent.com/4736168/108353827-e0a20d00-71e8-11eb-9967-1f33124f59c1.png)

**Comment by buddh4** [comment]
We should probably use the same style as in the stream. Maybe a widget would be nice.

**Comment by yurabakhtin** [comment]
@luke- @buddh4 PR https://github.com/humhub/humhub-modules-wiki/pull/159:

<img width="1455" alt="changed_topics_style" src="https://user-images.githubusercontent.com/6995524/108466680-13094400-7295-11eb-8f5d-7fe5d7c9470e.png">

**Comment by luke-** [comment]
Looks good. But, we need some extra padding here. (Only if topics are available, of course).

![image](https://user-images.githubusercontent.com/4736168/108487201-49e45780-729f-11eb-8edc-404769b19bd7.png)

**Comment by yurabakhtin** [comment]
@luke- Commit https://github.com/humhub/humhub-modules-wiki/pull/159/commits/45e26e6f94567359b7b19121ab9c65f6a32198ea:

I added the wrapper `<div class="wiki-content-info">` that has `margin-bottom: 5px;`, if it is not enough we can create an additional style class like `wiki-content-topics` with more space or use inline style, what is preferred?

<img width="724" alt="5px-space" src="https://user-images.githubusercontent.com/6995524/108491925-976bbf00-72b5-11eb-9fab-990bb32ead18.png">

**Comment by buddh4** [comment]
Please see https://github.com/humhub/humhub-modules-wiki/pull/161

**Comment by buddh4** [comment]
@yurabakhtin sorry did not know you where working on this
