### ISSUE TITLE
Bug view wiki page

### ISSUE THREAD

**Issue by nmalservet** [humhub/humhub-modules-wiki#26]
I have installed the wiki module on a server, but when i try to view a page, the result is a new html page with only the title, without the common frame humhub.
Here the full html result " <div class="panel panel-default">
    <div class="panel-body">

        <div class="row">
            <div class="col-lg-10 col-md-9 col-sm-9 wiki-content">
                <h1><strong>test2</strong></h1>
                <hr>

                <div class="markdown-render">" 

I think there is a bug on rendering after this widget : application.widgets.MarkdownViewWidget.

This wiki module works fine in localhost, but not in this installation on server.

**Comment by luke-** [comment]
Which PHP/HumHub Version?

**Comment by nmalservet** [comment]
Humhub version 0.11.1
PHP 5.3.3-7

**Comment by luke-** [comment]
HumHub requires at least 5.4

php.net/eol.php
