### ISSUE TITLE
Parse error: syntax error, unexpected '[' in /protected/libs/HMarkdown.php on line 109

### ISSUE THREAD

**Issue by tayzee** [humhub/humhub-modules-wiki#31]
Hi There, 

I have the above error when trying to view a page in my wiki. The problem is happening on my shared hosting account. On my local machine(a mac), where I configured Humhub and did some testing the articles open perfectly. Not sure why this is happening?

I have tried deleting the module and reinstalling it and redoing the articles and when I click save I receive the same error.

Please can someone assist?

Thanks,
Tay

**Comment by tayzee** [comment]
I've realised it might be the php version on the shared server, I will update once I have upgraded.

**Comment by wikibit** [comment]
I've the same issue
I'm on PHP - Version - 5.3.28
is there any solution or workaround?
(I cannot just upgrade PHP, I'm on a shared host, upgrading will impact a number of customers)

Olivier
