### ISSUE TITLE
Search unable find anythin

### ISSUE THREAD

**Issue by rishikesh09** [humhub/humhub-modules-wiki#39]
Native search functionality is not able to find anything from wiki pages, It can only search fro Main page but not from other pages.

**Comment by luke-** [comment]
Try to rebuild the search index.
https://www.humhub.org/docs/guide-admin-adv-search.html

**Comment by theexit** [comment]
After the rebuild the search funktion is working.
But if you add a new wiki site you have to rebuild the index again.
