### ISSUE TITLE
Differentiate between like and comment when sending notification e-mails

### ISSUE THREAD

**Issue by dakur** [humhub/humhub-modules-wiki#44]
I would really appreciate not to receive an e-mail on every post and like on a Wiki page, when I've just liked (not commented) it - it's so annoying. It's happening to me in here: https://community.humhub.com/s/contribution-core-development/wiki/page/view?title=Roadmap  
It would be OK if I comment something - then I'm probably waiting for a response. But if I just liked it, I don't care so much about comments and other likes. Plus it would be great to have an option for opt-in/opt-out.

**Comment by luke-** [comment]
We improved that part in 1.1
There will be no like mail notifications anymore.
The comment notifications will be combined.

In future we're going to improve that further...
