### ISSUE TITLE
Bug: Saving pages with non-ASCII titles broken

### ISSUE THREAD

**Issue by cboulanger** [humhub/humhub-modules-wiki#49]
Steps to reproduce:

1) Create a wiki page with a title that contains non-ASCII characters, such as "test äöüß"
2) Save page

Expected behaviour: The page is displayed in view mode
Actual behaviour: Page "Create new page" is displayed with no body, and a incorrectly encoded title such as "test %25C3%25B6%25C3%25A4%25C3%25BC%25C3%259F".

The page has been saved, but the response page is wrong. The same happens when editing a page with such a title.

**Comment by cboulanger** [comment]
Hello, to me at least this seems like a pretty major bug that should be addressed if you can reproduce it.

**Comment by buddha87** [comment]
Hi, I could not recreate the issue. Can you check your database encoding, do you have problems with umlauts anywhere else?

**Comment by cboulanger** [comment]
No, no problems otherwise. But I'll check if maybe the specific table has the wrong encoding.
