### ISSUE TITLE
Gestionnaire introuvable (after update 1.2 beta 2)

### ISSUE THREAD

**Issue by ygrosyeux** [humhub/humhub-modules-wiki#52]
Hi, 

after upgrade to 1.2 beta 2, WIKI's module is desactivate on all spaces.

When I try to put it "Activate" on space's configuration, I get an error message : 
 
![image](https://cloud.githubusercontent.com/assets/16611866/23618781/c0bb8c98-0291-11e7-9cf4-a66f1be96af2.png)

Issue ?

**Comment by ygrosyeux** [comment]
In Logging, I've got another informations : 
![image](https://cloud.githubusercontent.com/assets/16611866/23621589/ad4a9622-029b-11e7-86ad-3aaf99e6ae77.png)

**Comment by buddh4** [comment]
Try clearing your cache under "Administration -> Settings -> Advanced -> Cache  -> Flush Cache"

**Comment by ygrosyeux** [comment]
It's good ! Thx :)
