### ISSUE TITLE
[enhancement] Possibility to create a hierarchy of pages (like folders)

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub-modules-wiki#66]

**Comment by vxrdanny** [comment]
I would also like this.

**Comment by pingadi** [comment]
+1
hierarchy tree view on the left and the page view on the right would be awesome.

**Comment by arnfinnkristensen** [comment]
+1
Yes this is a great idee. Please implement :)

**Comment by buddh4** [comment]
This is definetly planed, the wiki module will be reworked after the v1.3 release.

**Comment by staxDB** [comment]
+1

**Comment by GuidoM12** [comment]
+1

**Comment by mirktmirkt** [comment]
Hello,

thank you for implementing categories!

1.2.0 (07 August, 2018
...
Enh: Added categories
...

Are you planning to implement multilevel categories?

**Comment by buddh4** [comment]
I think a next step for us would be a global overview of all member spaces in order to provide an additional level of abstraction and a better overview of all spaces, but a multi level index would also be great.

**Comment by akorsonsky** [comment]
is there a planning update with leveling of categories ?
