### ISSUE TITLE
Feature request: Linking between wiki pages

### ISSUE THREAD

**Issue by olekrisek** [humhub/humhub-modules-wiki#77]
Hello, I have just installed HumHub for our intranet, and I did the job converting from our old wiki from Redmine. What feature I really would like to see is the inter-linking feature many other wiki systems have using double brackets around words, to link to another wiki page about that word or term. 

Like this: 
`[[This goes to another wiki-page]]`

When the link does not match any other pages, it turns red, and blue if its active. Clicking a red link goes to a create form for that page. 

Its of course possible to link, but then I have to visit the other page first, obtain the link, and then go back and insert the link where I want it. The above method is much more easy.

**Comment by olekrisek** [comment]
I see there is already another syntax in place, working well. 

`[Wiki link](Name of wiki page)`

This works well for me. I have made a little pull request to enable a button to insert such a link just from a marked text - however, this file is outside the plugin directory, so I made it in humhub/humhub 

https://github.com/humhub/humhub/pull/3205

**Comment by Oremountainflorian** [comment]
Works fine, thanks for your suggestion and the implementation!
