### ISSUE TITLE
Editing Categories defaults to a Wiki Page inside the category

### ISSUE THREAD

**Issue by Felli** [humhub/humhub-modules-wiki#82]
Create a category, then add a wiki page within the category and try to edit the wiki category to add onto it and it will default to editing the wiki page inside the category instead, but I've also found that if there are no wiki pages inside the category you can edit the category itself.

**Comment by dpauli** [comment]
@Felli It does not work with the "fix". As I see the "fix" is only changing the variable name, but no logic.
