### ISSUE TITLE
Editing Categories defaults to a Wiki Page inside the category

### ISSUE THREAD

**Issue by dpauli** [humhub/humhub-modules-wiki#85]
I create an issue referencing to the #82 . There was a commit which does not take *any* effect. There was only a renaming of a variable.

The bug already exists:

1. Create a page as a category.
2. Create a sub page in this category.
3. Try to edit the category.

Result: You cannot do this. Clicking on *edit* will edit the first created sub page.

**Comment by Felli** [comment]
I haven't seen the issue since updating the wiki module to it's latest version. :thinking:
