### ISSUE TITLE
Links seem to be breaking wiki page

### ISSUE THREAD

**Issue by eplt** [humhub/humhub-modules-wiki#91]
Whenever I add a link inside the wiki post, it will break the page and the body of the page won't show up again in the page view or page edit. Anyone having similar problems? For pure text (including formatted text), I can save and view/edit fully after. But not with any page with I have included a link.

**Comment by buddh4** [comment]
Can you describe step by step what you do in order for me to reproduce this?

**Comment by eplt** [comment]
i can see this part in the html source view when i inspect the page. it is not showing on the page.


`



<textarea id="wikipagerevision-content_input" name="WikiPageRevision[content]" title="Page content" style="display:none;">testing this again.
  |  
  | [create a link](http://www.google.com)</textarea><div id="wikipagerevision-content" class="ProsemirrorEditor plainMenu" data-exclude='["resizeNav"]' data-include='[]' data-mentioning-url="/index.php?r=search%2Fsearch%2Fmentioning" data-placeholder="Page content" data-plugin-options='[]' data-preset="wiki" data-focus="" data-ui-widget="ui.richtext.prosemirror.RichTextEditor" data-ui-init="1"><div id="h644782w1" data-exclude='["resizeNav"]' data-include='[]' data-plugin-options='[]' data-preset="wiki" data-edit="1" data-ui-richtext="1" data-ui-widget="ui.richtext.prosemirror.RichText" data-ui-init="1" style="display:none">testing this again.
  |  
  | [create a link](http://www.google.com)</div><div class="richtext-oembed-container" style="display:none"></div></div><input type="file" id="wikipagerevision-content-file-upload" name="files[]" multiple="multiple" title="Upload file" data-upload-url="" data-upload-drop-zone="" data-upload-progress="" data-upload-preview="" data-upload-form="" data-upload-single="" data-upload-submit-name="fileList[]" data-upload-hide-in-stream="1" data-php-max-file-uploads="20" data-php-max-file-uploads-message="Sorry, you can only upload up to 20 files at once." data-ui-widget="file.Upload" data-ui-init="1" style="display:none">
 

`


<img width="973" alt="Screenshot 2019-03-23 at 14 55 55" src="https://user-images.githubusercontent.com/206939/54862870-eb916000-4d7b-11e9-92bf-2db8409c6ca1.png">

**Comment by eplt** [comment]
all i do is to add a link in the body of the page, and after saving the page, the body of the page will not work anymore, not in display mode or editor mode. but in the HTML, i can see the content in the html source.

**Comment by eplt** [comment]
just tested the latest release of the wiki module. it is still breaking any links in the body text. i just tried to add a link to http://www.bbc.com and the page body and editor will disappear. the title will still work. i am guessing it is not encoding certain characters so it breaks the js upon rendering. it is still in the html source, just can't display.

**Comment by buddh4** [comment]
- Did you check the [javascript console](http://docs.humhub.org/admin-troubleshooting.html)? 
- Which HumHub version is installed? 
- Are there any errors in `Administration -> Information -> Logging`?

**Comment by eplt** [comment]
WARN - humhub.modules.action: undefined
TypeError: humhub.modules.file.filterFileUrl is not a function. (In 'humhub.modules.file.filterFileUrl(tokens[idx].attrs[hrefIndex][1])', 'humhub.modules.file.filterFileUrl' is undefined)

**Comment by eplt** [comment]
Currently installed version: 1.3.12

**Comment by eplt** [comment]
no new error on Administration -> Information -> Logging

**Comment by sks7g** [comment]
I also had the same problem, I was running the system in debug mode, not in production mode. 
Have a look here... https://github.com/humhub/humhub/issues/2025

**Comment by eplt** [comment]
I can confirm that it is working now. yes, switching it to production mode works.
many thanks.

**Comment by buddh4** [comment]
Probably a caching issue, always try to clear the cache if such issues occure e.g. after an update.
