### ISSUE TITLE
Bug? - Parallel installed Wiki and Calendar module leads to error message

### ISSUE THREAD

**Issue by JamesWill1** [humhub/humhub-modules-wiki#97]
I installed the wiki module, which works fine at first.
Then I installed the calendar module.
If I now want to create a new page in the wiki and save the wiki page, this leads to the following error message:

![Screenshot_2019-08-05 yii base ErrorException](https://user-images.githubusercontent.com/53791777/62484292-28557500-b7ba-11e9-9249-4541cb77aa01.png)

If I uninstall the calendar module afterwards, the error message changes when saving a wiki page.

![Screenshot_2019-08-05 yii base ErrorException(1)](https://user-images.githubusercontent.com/53791777/62484271-1ffd3a00-b7ba-11e9-97c4-f6a2ee612a34.png)

The error is reproducible. And always happens after I install the calendar module.

**Comment by luke-** [comment]
Seems your server configuration is to restrictive (e.g. number of open files).

You can try to contact you server administration which may increase the limits for your account.

**Comment by JamesWill1** [comment]
Thank you very much for your answer!

We already suspected this possibility. Unfortunately our provider does not offer this possibility. They refer us to virtual servers. This is not included in our webhosting. But a virtual server means for us a very high expenditure and in addition we lack the know how.

Are there any software possibilities to limit the number of opened files?

**Comment by luke-** [comment]
Unfortunately not, HumHub is a very complex application with many required dependencies.
