### ISSUE TITLE
Protection against parallel editing

### ISSUE THREAD

**Issue by JamesWill1** [humhub/humhub-modules-wiki#99]
It is currently possible for two people to edit the same wiki page at the same time. There is no hint or block.
The problem is that the changes of the person who saves first are lost.
Is there a good workarround for this?

Many thanks and greetings!

**Comment by Ace2213** [comment]
Does it not appear in the edit history?

**Comment by Oremountainflorian** [comment]
We also thought about opening an issue because of this problem. Just blocking the page if some else is already editing would do it!

**Comment by buddh4** [comment]
Issue will continue in https://github.com/humhub/humhub-modules-wiki/issues/113
